config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "events#index"
  resources :events
  resources :users, only: [:index, :show]
  resources :event_attendees, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :event_attendees
  has_many :attendees, through: :event_attendees
  scope :past, -> { where('date <= ?', Time.now) }
  scope :future, -> { where('date > ?', Time.now) }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :event
  belongs_to :attendee, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: "creator_id", class_name: "Event"
  has_many :event_attendees, foreign_key: "attendee_id"
  has_many :attended_events, through: :event_attendees, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  def create
    @event_attendee = EventAttendee.new(event_id: params["event_id"], attendee_id: params["attendee_id"])

    @event_attendee.save

    redirect_to event_path(params["event_id"])
  end

  def destroy
    @event_attendee = EventAttendee.find_by(event_id: params["event_id"],attendee_id: params["attendee_id"])
    @event_attendee.destroy

    redirect_to event_path(params["event_id"])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to event_path(@event.id)
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to event_path(@event.id)
    else
      render :new
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to root_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :date, :location)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @created_events = @user.created_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_with model: @event do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :date %>
  <%= form.datetime_select :date %>
  <%= form.label :location %>
  <%= form.text_field :location %>
  <%= form.submit "Submit" %>
<% end %>

app/views/events/index.html.erb
<h1>Events</h1>

<h2>Upcoming: </h2>
<ul>
  <% @events.future.each do |event| %>
    <li>
      <a href="/events/<%= event.id %>">
        <%= event.title %>
      </a>
      - <%= event.date %>
    </li>
  <% end %>
</ul>

<h2>Past: </h2>
<ul>
  <% @events.past.each do |event| %>
    <li>
      <a href="/events/<%= event.id %>">
        <%= event.title %>
      </a>
      - <%= event.date %>
    </li>
  <% end %>
</ul>


<% if user_signed_in? %>
  <%= button_to "Create Event", new_event_path, method: :get  %>
<% end %>

app/views/events/new.html.erb
<h1>New Event!</h1>

<%= form_with model: @event do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :date %>
  <%= form.datetime_select :date %>
  <%= form.label :location %>
  <%= form.text_field :location %>
  <%= form.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

<p>Date: <%= @event.date %></p>

<p>Location: <%= @event.location %></p>

<p>Creator: <%= @event.creator.username %>

<p>Attendees: </p>
  <ul>
    <% @event.attendees.each do |attendee| %>
      <li>
        <a href="/users/<%= attendee.id %>">
          <%= attendee.username %>
        </a>
      </li>
    <% end %>
  </ul>

<% if user_signed_in? %>
  <% if current_user != @event.creator %>
    <% if !@event.event_attendees.exists?(attendee_id: current_user.id) %>
      <%= button_to "I am attending this event.", event_attendees_path, params: { event_id: @event.id, attendee_id: current_user.id }%>
    <% else %>
      <%= button_to "I am no longer attending this event.", event_attendee_path, method: :delete, params: { event_id: @event.id, attendee_id: current_user.id } %>
    <% end %>
  <% else %>
    <%= button_to "Edit", edit_event_path, method: :get %>
    <%= button_to "Delete", event_path, method: :delete, data: { confirm: "Are you sure?" }%>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="topnav-center" style="text-align:right;">
      <%= link_to "Events", events_path, method: :get  %>
      <%= link_to "Users", users_path, method: :get  %>
      <% if user_signed_in? %>
        <%= link_to "My Profile", user_path(current_user.id), method: :get %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Login", new_user_session_path, method: :get  %>
      <% end %>
    </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <a href="/users/<%= user.id %>">
        <%= user.username %>
      </a>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<p>Email: <%= @user.email %></p>

<h2>Created Events:</h2>
<ul>
  <% @created_events.each do |event| %>
    <li>
      <a href="/events/<%= event.id %>">
        <%= event.title %>
      </a>
      - <%= event.date %>
    </li>
  <% end %>
</ul>

<h2>Attended Events:</h2>
<p>Upcoming: </p>
<ul>
  <% @user.attended_events.where('date > ?', Time.now).each do |event| %>
    <li>
      <a href="/events/<%= event.id %>">
        <%= event.title %>
      </a>
      - <%= event.date %>
    </li>
  <% end %>
</ul>
<p>Past: </p>
<ul>
  <% @user.attended_events.where('date <= ?', Time.now).each do |event| %>
    <li>
      <a href="/events/<%= event.id %>">
        <%= event.title %>
      </a>
      - <%= event.date %>
    </li>
  <% end %>
</ul>